[package]
name = "bevy-ball-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
rand = "0.8.5"
bevy_tweening = "0.8.0"
bevy_xpbd_2d = "0.2"